# GitAction 名称
name: Build Docs and Deploy

# 此CI/CD触发时的事件 push:在代码提交时自动触发
on:
  push:
    branches:
      - main

# 一个 CI/CD 的工作流有许多 jobs 组成，比如最典型的 job 是 lint，test，build等，这里起名 build-and-deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行workflow的服务器系统：ubuntu最新版本
    strategy:
      with:
        node-version: 16
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
